function PlotaArquitetura(rat_num,slice_num)
%CREATEFIGURE(YMATRIX1, YMATRIX2, Y1)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  area matrix data
%  Y1:  stairs y
%  Auto-generated by MATLAB on 31-Aug-2017 09:09:35

rato = sprintf('%d_%d',rat_num,slice_num);

file = sprintf('/home/vittorfp/Documentos/Neuro/Dados/percentuals/R%s_times.mat',rato);
load(file);

folder2 = '/home/vittorfp/Documentos/Neuro/Dados/scaled/';
file = sprintf('%sR%s_scaled.mat',folder2,rato);		
load(file);
clear file folder2 rato

r = find(Estados == 1);
s = find(Estados == 2);
wr = find(Estados == 3);
wa = find(Estados == 4);

REM_SLEEP = zeros(1,length(Delta_scaled));
SW_SLEEP = zeros(1,length(Delta_scaled));
WAKE_R = zeros(1,length(Delta_scaled));
WAKE_A = zeros(1,length(Delta_scaled));

REM_SLEEP(r) = 1;
SW_SLEEP(s) = 1;
WAKE_R(wr) = 1;
WAKE_A(wa) = 1;

clear r s wr wa

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(4,1,1,'Parent',figure1);
hold(subplot1,'on');

YMatrix1 = [Delta_scaled' Theta_scaled' Emg_scaled'];
clear Delta_scaled Theta_scaled Emg_scaled

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','Delta');
set(plot1(2),'DisplayName','Theta');
set(plot1(3),'DisplayName','EMG');

% Create title
title('Classificação de sono');

% Create ylabel
ylabel('Potência');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[1 length(Estados)]);
box(subplot1,'on');
grid(subplot1,'on');
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(4,1,2,'Parent',figure1);
hold(subplot2,'on');

ymatrix2 = [ WAKE_R' WAKE_A' SW_SLEEP' REM_SLEEP'];

% Create multiple lines using matrix input to area
area1 = area(ymatrix2,'Parent',subplot2,'LineWidth',1);
set(area1(4),...
	'FaceColor',[0.333333333333333 0.0784313725490196 0.788235294117647]);
set(area1(3),...
	'FaceColor',[0.333333333333333 0.592156862745098 0.866666666666667]);
set(area1(2),...
	'FaceColor',[0.333333333333333 0.862745098039216 0.784313725490196]);
set(area1(1),...
	'FaceColor',[0.784313725490196 0.941176470588235 0.784313725490196]);


legend(area1,'ACTIVE','REST','SWS' ,'REM');

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[1 length(Estados)]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 1]);
box(subplot2,'on');
grid(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'YTick',[]);
% Create legend
legend(subplot2,'show');

% Create axes
axes1 = axes('Parent',figure1,...
	'Position',[0.13 0.11 0.775 0.376827956989247]);
hold(axes1,'on');

Y1 = Estados;

% Create stairs
stairs(Y1,'Parent',axes1);

% Create xlabel
xlabel('Epocas de 5s');

% Create ylabel
ylabel('Estado');

xlim(axes1,[1 length(Estados)]);	
ylim(axes1,[0.5 4.5]);
clear Estados;

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'YTick',[1 2 3 4],'YTickLabel',{'REM','SWS','WAKE R','WAKE A'});
